# syntax = docker/dockerfile:1
FROM ruby:3.2.2-slim
WORKDIR /rails

# devはビルドツール常備
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential default-libmysqlclient-dev git pkg-config curl \
      libjemalloc2 libvips python3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# 開発向け設定（dev/testも入れるため BUNDLE_WITHOUT は未設定）
ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

# 非rootユーザー
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    mkdir -p /usr/local/bundle && chown -R rails:rails /usr/local/bundle /rails
USER 1000:1000

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
