# render.yaml（Blueprint 最小＋素直な構成）
databases:
  - name: fasty-db
    databaseName: fasty_prod
    user: fasty

services:
  - type: web
    name: fasty-web
    runtime: ruby
    buildCommand: bundle install && bundle exec rails assets:precompile
    preDeployCommand: bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: fasty-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
