# config/database.yml

# Docker（dev/test）は MySQL を使用
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE", "fasty_app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_TEST_DATABASE", "fasty_app_test") %>

# Heroku（production）は Postgres を使用（DATABASE_URL をそのまま参照）
# ※ default を継承しない（adapter が mysql2 になってしまうため）
production:
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
